version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - echo Installing dependencies
      - npm install
      - npm install -g mocha

  build:
    commands:
      - echo Running tests
      - npm test
      - echo Building and tagging Docker image
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 356370655928.dkr.ecr.ap-southeast-2.amazonaws.com
      - docker build -t node-api-test .
      - docker tag node-api-test:latest 356370655928.dkr.ecr.ap-southeast-2.amazonaws.com/node-api-test:latest

  post_build:
    commands:
      - echo Pushing to ECR
      - docker push 356370655928.dkr.ecr.ap-southeast-2.amazonaws.com/node-api-test:latest
